name: Lab02 Reuse and Artifacts
run-name: Lab02 - ${{ github.actor }} is calling Composite Actions 🚀
permissions: read-all
on:
  workflow_dispatch:
jobs:
  run-composite:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: dotnet-build
        uses: ./.github/actions/build-dotnet-app
        with:
          folder-path: "app/uptodate-app"
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app:
          path: ${{ steps.dotnet-build.outputs.output-directory-path }}

